#docker-compose.yml
version: '3.8'

services:

  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - sendthistomyfuture-me
    volumes:
     - ./mongo_data:/data/db
    env_file:
      - .env

  server:
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - sendthistomyfuture-me

networks:
  sendthistomyfuture-me:
    driver: bridge
